### ISSUE TITLE
Pop-ups open

### ISSUE THREAD

**Issue by dhmusman** [cycopay/cycopay-wp#1]
Hi,
We are facing one issue on our multiple website with divi theme only, issue you can see in the screenshot below. whenever we visit the website blank pop up open if we deactivate your plugin then issue does not occur.
![cl1](https://user-images.githubusercontent.com/12247463/174302399-71e7c1b9-0e68-4c93-89a6-652c7c003f77.png)

**Comment by maximverse** [comment]
This has been resolved with the latest update. Thank you.

**Comment by dhmusman** [comment]
Thanks.
